features/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'features'
urlpatterns = [
    path('members/', views.members, name='members'),
    path('craftsmen/', views.craftsmen, name='craftsmen'),
    path('craftsman_detail/<int:craftsman_id>/', views.craftsman_detail, name='craftsman_detail'),
    path('AboutUs/', views.about_us, name='AboutUs'),
    path('career/', views.career, name='career'),
    path('interview/', views.interview, name='interview'),
    path('submit_rating/<int:craftsmanId>/', views.submit_rating, name='submit_rating'),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

job/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'job'
urlpatterns = [
    path('', views.jobs_list, name='job_list'),
    path('add', views.add_job, name='add_job'),
    path('your_jobs', views.your_jobs, name='your_jobs'),
    path('jobs/<int:job_id>/delete/', views.delete_job, name='delete_job'),
    path('<int:id>', views.edit_job, name='edit_job'),
    path('<str:slug>', views.job_details, name='job_details'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'pages'
urlpatterns = [
    path('', views.index, name='index'),
    path('home', views.home, name='home'),
    path('feedback', views.send_message, name='feedback'),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profiles/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from project.settings import MEDIA_ROOT
from . import views

from profiles.views import ChangePasswordView


app_name = 'profiles'

urlpatterns = [
    path('', views.profile, name='profile'),
    path('edite/', views.edite, name='edite'),
    path('password-change/', ChangePasswordView.as_view(), name='password_change'),

    path('others/', views.others, name='others'),
    path('trans/', views.trans, name='trans'),
    path('<int:id>', views.other, name='other'),
    path('<int:rateid>/', views.submit_rating, name='submit_rating'),

    path('recommendations/', views.Recommendation_view, name='Recommendation_view'),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.urls import path, include, re_path
from django.conf.urls.i18n import i18n_patterns


urlpatterns = [

    path("i18n/", include("django.conf.urls.i18n")), #https://docs.djangoproject.com/en/4.2/topics/i18n/translation/#django.views.i18n.set_language ,
]


urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('jobs/', include('job.urls', namespace='jobs')),
    path('', include('pages.urls', namespace='pages')),
    path('profile/', include('profiles.urls', namespace='profiles')),
    path('registration/', include('registration.urls', namespace='registration')),
    path('features/', include('features.urls', namespace='features')),
    # هنا انا استخدمت كل ال methods الداخلية فى ال django
    # الجاهزة اللى موجودة فى ال registration
    # اللى هى كتبناها فى فايل txt

    path("accounts/", include("django.contrib.auth.urls")),
    # عشان اوصل لمكان ال template
    # واعرف اساميهم امشى على نفس المسار اللى مكتوب
)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

registration/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'registration'
urlpatterns = [
    path('signin', views.LoginPage, name='signin'),
    path('signup', views.SignupPage, name='signup'),
    path('logout/', views.LogoutPage, name='logout'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profiles/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms import widgets
from .models import Profile
from profiles import models


class UserForm(forms.ModelForm):
    email = forms.EmailField()
    password = forms.PasswordInput()

    class Meta:
        model = User
        fields = ['username', 'email']
        exclud = ['password',]


class ProfileForm(forms.ModelForm):
    # dob = forms.DateField(required=False)
    class Meta:
        model = models.Profile
        fields = ['image', 'phone_number', 'city', 'dob', 'gender', 'education',
                  'experience', 'language', 'tecskill', 'softskill', 'bio', 'cv', 'file' , 'face']
        widgets = {
            'image': widgets.FileInput(attrs={
                'class': 'fa fa-camera'
            }),
            'dob': widgets.DateInput(attrs={
                'type': 'date'
            }),
            'cv': widgets.FileInput(attrs={
                'class': 'cv_input'
            }),
            'file': widgets.FileInput(attrs={
                'class': 'file_input'
            })
        }

profiles/views.py
import datetime
from audioop import reverse
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserForm, ProfileForm
from .models import Profile, Rate, Recommendation_Model
from django.urls import reverse_lazy
from django.contrib.auth.views import PasswordChangeView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator
from django.db.models import Avg, Q
from django.urls import reverse

# Create your views here.
from third_party.views import make_messages, translate_po_file, compile_translations 
    
@login_required()
def profile(request):
    profile = Profile.objects.get(user=request.user)
    return render(request,  'profiles/profile.html', {'profile': profile})


@login_required()
def edite(request):
    try:
        profile = Profile.objects.get(user=request.user)
    except:
        print("No Profile")
        profile = None
    # userform = UserForm()
    # profileform=ProfileForm()
    if request.method == 'POST':
        userform = UserForm(request.POST, request.FILES, instance=request.user)
        profileform = ProfileForm(
            request.POST, request.FILES, instance=profile)
        # date_profile = validated_data['dob']
        # transformed_date = datetime.datetime.strptime(date_profile, '%m/%d/%Y').strftime('%Y-%m-%d')
        # print(date_profile)
        if userform.is_valid() and profileform.is_valid():
            userform.save()
            profileform.save()
            print("Saved")
            # myprofile=profileform.save()
            # لو التاريخ فيه مشكلة فى ترتيب الشهور والايام
            # حوليه قبل ما يتحفظ
            # بالسطر دة
            # print(myprofile.dob)
            # دة لتحويل التاريخ ل str
            # date_in_str = str(myprofile.dob)
            # دة لتحويله من صيغة الى صيغة تانية
            # تكتب فى strptime الصيغة اللى ها تحولى منها
            # فى strftime الصيغة الى ها تحولى ليها
            # transformed_date = datetime.datetime.strptime(date_in_str, '%m/%d/%Y').strftime('%Y-%m-%d')
            # transformed_date = str(transformed_date)
            # print(transformed_date)
            return redirect('profiles:profile')
        else:
            print("Error In Saved")
            print(profileform.errors)
            userform = UserForm(instance=request.user)
            profileform = ProfileForm(instance=profile)
    else:
        userform = UserForm(instance=request.user)
        profileform = ProfileForm(instance=profile)

    return render(request, 'profiles/edit.html',
                  {
                      'userform': userform,
                      'profileform': profileform})


class ChangePasswordView(SuccessMessageMixin, PasswordChangeView):
    template_name = 'profiles/change_password.html'
    success_message = "Successfully Changed Your Password"
    success_url = reverse_lazy('password_change_done')
    # New Password Admin1990

    # spider admin5555
    # spider (newpassword) admin7777

    # Sharaf Section


def search_profiles(query):
    query = query.strip()  # Remove leading and trailing whitespace from the query

    if not query:
        return get_all_profiles()  # Return an empty queryset when the query is empty or contains only whitespace

    return Profile.objects.filter(
        Q(user__username__icontains=query) | Q(email__icontains=query)
    ).annotate(
        average_quality=Avg('rate__RAtingQuality')
    ).order_by('-average_quality', '-id')

def get_all_profiles():
    return Profile.objects.all().annotate(
        average_quality=Avg('rate__RAtingQuality')
    ).order_by('-average_quality', '-id')

def others(request):
    query = request.GET.get('q')
    user = request.user

    if user.is_authenticated and query:
        Recommendation_Model.objects.create(User=user, Search_Words=query)

    if query :
        others = search_profiles(query) 
            
    elif user.is_authenticated:
        others = Recommendation_view(request)
    
    else :
        others = get_all_profiles()

    paginator = Paginator(others, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'users': page_obj, 'query': query}
    return render(request, 'profiles/others.html', context)



def other(request, id):
    profile = Profile.objects.get(id=id)
    Revq = profile.average_quality()
    Revs = profile.average_speed()
    Revm = profile.average_moralistic()
    rating_details = Rate.objects.filter(RA_Other=profile)
    context = {'user': profile ,'rating_details': rating_details , 'RAtingQuality':Revq ,
                'RAtingSpeed':Revs , 'RAtingMoralistic':Revm
                }
    return render(request, 'profiles/other.html', context)

def submit_rating(request, rateid):
    if request.method == 'POST':
        user = request.user
        other = Profile.objects.get(id=rateid)
        quality_rating = request.POST.get('quality_rating')
        speed_rating = request.POST.get('speed_rating')
        moralistic_rating = request.POST.get('moralistic_rating')
        description = request.POST.get('description')
        existing_rating = Rate.objects.filter(RAUser=user, RA_Other=other).first()
        
        if existing_rating:
            # An existing rating was found, update it with new values
            if quality_rating is None and speed_rating is None and moralistic_rating is None and description == '':
                # No rating or description is provided, inform the user to fill in at least one of the fields
                messages.warning(request, "Please fill in at least one of the rating fields or the description field.")
            else:
                existing_rating.RAtingQuality = quality_rating
                existing_rating.RAtingSpeed = speed_rating
                existing_rating.RAtingMoralistic = moralistic_rating
                existing_rating.RADescription = description
                existing_rating.save()
                messages.success(request, "The rating has been updated successfully.")
        else:
            # No rating exists for this user and profile, create and save a new Rating object
            if quality_rating is None and speed_rating is None and moralistic_rating is None and description == '':
                # No rating or description is provided, inform the user to fill in at least one of the fields
                messages.warning(request, "Please fill in at least one of the rating fields or the description field.")
            else:
                rating = Rate(
                    RAUser=user,
                    RA_Other=other,
                    RAtingQuality=quality_rating,
                    RAtingSpeed=speed_rating,
                    RAtingMoralistic=moralistic_rating,
                    RADescription=description
                )
                rating.save()
                messages.success(request, "The evaluation of the profile has been completed successfully.")
        
        return redirect('profiles:other', id=rateid)

def Recommendation_view(request):
    user = request.user  # Assuming the logged-in user is requesting the recommendations
    search_words = Recommendation_Model.objects.filter(User=user).values_list('Search_Words', flat=True)
    search_words = search_words[::-1]
    # Additional logic goes here

    all_searched_words = set()

    for word in search_words:
        results = search_profiles(word)  # Assuming search_profiles() is the function to search in the database
        for profile in results:
            if profile != user.profile:
                all_searched_words.add(profile)  # Append the search results to the set excluding the logged-in user's profile
    
    all_users = list(get_all_profiles())  # Retrieve all profiles and store them in a list

    combined_list = list(all_searched_words)  # Convert all_searched_words to a list

    for user_profile in all_users:
        if user_profile not in all_searched_words and user_profile != user.profile:
            combined_list.append(user_profile)  # Append unique user profiles to the list

    return combined_list

def trans (request):
    make_messages()
    translate_po_file()
    compile_translations()
    return render(request, 'profiles/tran.html')
  

profiles/templates/profiles/change_password.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/pass.css' %}">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <title>ChangePassword</title>
</head>

<body>
    <center>
        <div class="form-content my-3 p-3">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-5">
                        <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                            <br>


                            <div class="card-header justify-content-center">
                                <br />
                                <h3 class="font-weight-light my-4 text-center">Change Your Password</h3>
                                <br>
                                <br>
                            </div>
                            {% if form.errors %}
                            <div class="alert alert-danger alert-dismissible" role="alert">
                                <div id="form_errors">
                                    {% for key, value in form.errors.items %}
                                    <strong>{{ value }}</strong>
                                    {% endfor %}
                                </div>



                            </div>
                            {% endif %}

                            <div class="card-body">
                                <form method="POST">
                                    {% csrf_token %}
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group">

                                                <input type="password" name="old_password" autocomplete="new-password"
                                                    class="form-control" required id="id_old_password"
                                                    placeholder="Enter Old Password" />
                                                <span>
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group">

                                                <input type="password" name="new_password1" autocomplete="new-password"
                                                    class="form-control" required id="id_new_password1"
                                                    placeholder="Enter New Password" />
                                                <span>
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group">

                                                <input type="password" name="new_password2" autocomplete="new-password"
                                                    required id="id_new_password2" class="form-control"
                                                    placeholder="Confirm New Password" />
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group mt-0 mb-1">
                                                <button type="submit" class="col-md-12 btn btn-dark" id="reset">Update
                                                    Password</button>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </center>
</body>

profiles/templates/profiles/profile.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/mayarstyle.css' %}">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">


    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <!--main Templete-3 Css File-->
    <link rel="stylesheet" href="{% static 'css/morsy.css' %}">

    <link rel="stylesheet" href="{% static 'css/style.css'%}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'css/morsy.min.css' %}">
    <!--Google Fonts-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Cairo:wght@300;400;700&family=Fraunces:opsz,wght@9..144,700&family=Montserrat:wght@500;700&family=Open+Sans:wght@400;700&display=swap"
        rel="stylesheet">
    <title>Profile</title>
</head>

<body>
    <Header>
        <div class="container">
            <a href="{% url 'pages:index' %}" class="logo">
                <h2 style="color: #fff;">Joblance</h2>
            </a>
            <ul class="links">
                <li><a href="{% url 'pages:home' %}">Home</a></li>
                <li><a href="{% url 'jobs:job_list' %}">Browse Jobs</a></li>
                <li><a href="{% url 'profiles:others' %}"> {% trans "Hire Now" %}</a></li>
                <li>
                    <a href="#" class="io">More</a>
                    <!-- Start Megamenu -->
                    <div class="mega_menu">
                        <div class="image">
                            <img src="{% static 'img/images/megamenu.png' %}" alt="">
                        </div>
                        <ul class="links_one">
                            <li>
                                <a href="{% url 'jobs:add_job' %}"><i class="far fa-clipboard fa-fw"></i>Post a job</a>
                            </li>
                            <li>
                                <a href="{% url 'features:AboutUs' %}"><i class="far fa-chart-bar fa-fw"></i>About Us</a>
                            </li>
                            
                            <li>
                                <a href="{% url 'features:career' %}"><i class="far fa-comments fa-fw"></i>Career Advices</a>
                             </li>
                        </ul>
                        <ul class="links_one">
                            <li>
                                <a href="{% url 'features:craftsmen' %}"><i class="far fa-building fa-fw"></i>Craftsmen</a>
                            </li>

                            <li>
                                <a href="{% url 'pages:feedback' %}"><i class="far fa-check-circle fa-fw"></i>Send
                                    feedback</a>
                            </li>
                            <li>
                                <a href="{% url 'features:interview' %}"><i class="far fa-comments fa-fw"></i>Interview Tips</a>
                             </li>
                        </ul>
                    </div>
                    <!-- End Megamenu -->
                </li>
            </ul>
            <div class="col-xl-3 col-lg-3 d-none d-lg-block">
                <div class="Appointment">

                    {% if request.user.is_authenticated %}
                    <div class="d-none d-lg-block">
                        <a href="{% url 'registration:logout' %}" class="boxed-btn3">Logout</a>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>

    </Header>
    
    <section>
        <center>
            <div class="profile">

                <div class="card">

                    <div class="image">
                        <img src="{{ user.profile.image.url }}" alt="face">
                    </div>
                    <div class="content">
                        <h2>{% trans "{{profile.user}}" %}</h2>
                    </div>

                    <div class="main">
                        <p style="color:black"><i class="fa fa-envelope ">
                            </i> {{profile.user.email}}</p>
                        <p style="color:black"><i class="fa fa-phone">
                            </i> {{profile.phone_number}}</p>
                        <p style="color:black"><i class="fas fa-map-marker-alt fa-fw" aria-hidden="true">
                            </i> {% trans "{profile.city}" %}</p>
                        <p style="color:black"><i class="fa fa-calendar-o">
                            </i> {{profile.dob}}</p>
                        <p style="color:black"><i class="fa fa-user ">
                            </i> {{profile.gender}}</p>
                    </div>
                    <br />
                    <div class="us" style="margin-top: 0px;
           padding-top: 0px;
           padding :10px;
           color: black;
           font-size: 1rem;
           border-radius: 5px;
           border: 1px solid black;
           height: 250px;
           text-align: left;
           display: block">
                        <h3>CV</h3>
                        <i class="fa fa-file-pdf-o" aria-hidden="true" style="font-size: 30px;"></i> <strong
                            style="padding-left: 10px;"><a href="{{ profile.cv.url }}" style="color: black;text-decoration:none;
          ">{{profile.cv}}</a></strong>
                        <hr>
                        <h3>Certification</h3>
                        <i class="fa fa-file-pdf-o" aria-hidden="true" style="font-size: 30px;"></i> <strong
                            style="padding-left: 10px;"><a href="{{ profile.file.url }}" style="color: black;
           text-decoration:none;">{{profile.file}}</a></strong>
                    </div>
                    
                    <br>

                    <a href="{% url 'jobs:your_jobs' %}">
                        <button class="edite">My Joblist</button>
                    </a>
                   
                    <br><br>


                    <div class="infomayar" style="margin-top: 0px;
           padding-top: 0px;
           padding :10px;
           color: black;
           font-size: 1rem;
           border-radius: 5px;
           border: 1px solid black;
           height: 500px;
           text-align: left;
           display: block">
                        <h4>Education</h4>
                        {{profile.education}}
                        <hr>
                        <h4>Experience</h4>
                        {{profile.experience}}
                        <hr>
                        <h4>Language</h4>
                        {{profile.language}}
                        <hr>
                        <h4>Technical Skills</h4>
                        {{profile.tecskill}}
                        <hr>
                        <h4>Soft Skills</h4>
                        {{profile.softskill}}
                    </div>
                    <br />

                    <a href="{% url 'profiles:edite' %}">
                        <button class="edite">Edit Profile</button>
                    </a>
                    <br />
                    <a href="{% url 'profiles:password_change' %}">
                        <button class="pass">Change Password</button>
                    </a>


                </div>
            </div>

        </center>
    </section>

    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <section style="margin-top: 330px;">

        <div class="spikes"></div>

<!--Start Footer-->
<footer>
    <div class="container">


        <div class="box">
            <h3 style="color: #fff;">Joblance</h3>
            <br>
            <ul class="social">
                <li>
                    <a href="#" class="facebook">
                        <i class="fab fa-facebook-f"></i>
                    </a>
                </li>
                <li>
                    <a href="#" class="twitter">
                        <i class="fab fa-twitter"></i>
                    </a>
                </li>
                <li>
                    <a href="#" class="youtube">
                        <i class="fab fa-youtube"></i>
                    </a>
                </li>
            </ul>
            <br>
            <p class="text">
                A big world in a small place
            </p>
        </div>

      
        <div class="box">
            <ul class="links">
                <li>
                    <a href="{% url 'features:members' %}">Members</a>
                </li>
                <li>
                    <a href="{% url 'jobs:job_list' %}">Find a Job</a>
                </li>
                <li>
                    <a href="{% url 'profiles:others' %}">Hire Now</a>
                </li>
                <li>
                    <a href="{% url 'features:craftsmen' %}">Craftsmen</a>
                </li>
                <li>
                    <a href="{% url 'pages:feedback' %}"><i></i>Feedback</a>
                </li>
            </ul>
        </div>
        <div class="box">
            <div class="line">
                <i class="fas fa-map-marker-alt fa-fw"></i>
                <div class="info">
                    Cairo, Egypt
                </div>
            </div>
            <div class="line">
                <i class="far fa-clock fa-fw"></i>
                <div class="info">
                    Joblance Team Working Hours: 08:00-04:00
                </div>

            </div>
            <div class="line">
                <i class="fas fa-phone-volume fa-fw"></i>
                <div class="info">
                    +201151261692
                    +201095625946
                </div>
            </div>
        </div>

    </div>
   <p class="copyright">Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | Made by <a href="{% url 'features:members' %}" target="_blank">Joblance Team</a> </p>
   

</footer>
<!--End Footer-->
    </section>
</body>

</html>

profiles/templates/profiles/search.html
<!DOCTYPE html>
<html>

<head>
  <title>User Search</title>
</head>

<body>
  <form method="GET">
    <input type="text" name="q" placeholder="Search users">
    <button type="submit">Search</button>
  </form>
  {% if users %}
  <ul>
    {% for user in users %}
    <li>{{ user.fname }} {{ user.lname }}</li>
    {% endfor %}
  </ul>
  {% else %}
  <p>No users found.</p>
  {% endif %}
</body>

</html>
This template displays a search form with a text input and a submit button. It then checks if the users queryset is not
empty, and if so, loops over the users and displays their first and last names in an unordered list. If users is empty,
it displays a message saying no users were found.

profiles/templates/profiles/tran.html
{% load i18n %}

<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>

    <form action="{% url 'set_language' %}" method="post">
        {% csrf_token %}
        <input name="next" type="hidden" value="{{ redirect_to }}">
        <select name="language">
            {% get_current_language as LANGUAGE_CODE %}
            {% get_available_languages as LANGUAGES %}
            {% get_language_info_list for LANGUAGES as languages %}
            {% for language in languages %}
            <option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %} selected{% endif %}>
                {{ language.name_local }} ({{ language.code }})
            </option>
            {% endfor %}
        </select>
        <input type="submit" value="Go">
    </form>

</body>
</html>